### ISSUE TITLE
bad value on personnal data

### ISSUE THREAD

**Issue by tenev911** [hipay/hipay-fullservice-sdk-php#34]
Hi
on this line
https://github.com/hipay/hipay-fullservice-sdk-php/blob/3272b6cc82ff93c7fd7a94e0738f81e4a986b93b/lib/HiPay/Fullservice/Gateway/Mapper/PersonalInformationMapper.php#L45

`$firstname = isset($source['firstname']) ?: null;`

$firstname will be `true` instead of the firstname.

it must be:

`$firstname = isset($source['firstname']) ? $source['firstname'] : null;`

**Comment by jprotin** [comment]
Hi @tenev911 

Thank you for your comment, we will fix very quickly.

**Comment by jprotin** [comment]
Hi Tonev911,

https://github.com/hipay/hipay-fullservice-sdk-php/pull/35 

It's merged in develop and we will make a new release next week (22/03 or 23/03)

Many thanks !
