### ISSUE TITLE
Library TLS support

### ISSUE THREAD

**Issue by webmake** [hipay/hipay-fullservice-sdk-php#36]
SimpleHTTPClient doesn't work no longer, since TLS 1.0 is disabled

**Comment by etiennelandais** [comment]
Hello !

Thank you for Bringing this issue.

What version of openssl are you in ? 

In our library we do not force the SSL version used so the default version will be determined by SSL/TSL Handshake. Your server we'll try to negociate with our serverthe best algorithm to use.

If your server only support TSL 1.0, Curl we'll use TSL1.0 (it's the case if your version of openssl is 1.0.0h or older).

There is also a known bug in older curl version https://github.com/curl/curl/issues/700

**Comment by webmake** [comment]
https://support.hipay.com/hc/en-us/articles/360000298625-HiPay-TLS-1-0-Disablement

**Comment by webmake** [comment]
There is the way to determine if constant exists, still better than full system upgrade due library favor, I expect that installing library would work out of the box, instead I got 503 exception and had to debug, more over some links worked as `token` invoke, but `order` creation didn't. So this is only not proper avoidance to do not touch library.
