### ISSUE TITLE
Bug in comparison

### ISSUE THREAD

**Issue by webmake** [hipay/hipay-fullservice-sdk-php#38]
Recently I had to debug, how code works, and something caught my attention:
https://github.com/hipay/hipay-fullservice-sdk-php/blob/master/lib/HiPay/Fullservice/Gateway/Client/GatewayClient.php#L195
```
        if (!is_null($amount)) {
            if (!is_float($amount) && !($amount > 0.01)) {
                throw new InvalidArgumentException("Amount must be a float type and greater than 0.01");
            } else {
                $maintenanceRequest->amount = $amount;
            }
        }
```
this condition doesn't work with really invalid values: for example 0.002 https://3v4l.org/17kOX, but exception declares supposed to work.

More over, why `$maintenanceRequest->operation = $operationType` has no option to be passed within $maintenanceRequest itself like amount, operation_id?

**Comment by etiennelandais** [comment]
Hello ! 
Thank you for briging this issue.
For the first part of the issue, the condition we'll be fix and release soon.

`
if (!is_float($amount) || $amount < 0.01) {
                throw new InvalidArgumentException("Amount must be a float type and greater than 0.01");
            } else {
                $maintenanceRequest->amount = $amount;
            }
`
For the second part of this issue, i'm sorry but I don't really get what you mean by 

> $maintenanceRequest->operation = $operationType has no option to be passed within $maintenanceRequest itself like amount

Please, can you explain it ?

Thanks

**Comment by webmake** [comment]
Hello,

it's about `GatewayClient::requestMaintenanceOperation()`  when passing `MaintenanceRequest` filled object, but on [assignment](https://github.com/hipay/hipay-fullservice-sdk-php/blob/master/lib/HiPay/Fullservice/Gateway/Client/GatewayClient.php#L192) will loose filled `operation` attribute original value.
For example:
`$maintenanceRequest->amount` assignment has a check `!is_null($amount)`,
`$maintenanceRequest->operation_id` also has a check `!is_null($operationId)`,
so `amount` and `operation_id` attributes won't loose their primary values if we call `requestMaintenanceOperation($arg1, $arg2, null, null, $maintenanceRequest)`

**Comment by etiennelandais** [comment]
Ok it's clear now !

I agree that `requestMaintenanceOperation` should only be drived by the `MaintenanceRequest` object but for backward compatibilty reason it's realy touchy to rework that part of the code (and it's working, just a bit confusing).

But i can add something like that :
```
       if ($maintenanceRequest->operation === null && $operationType === null) {
            throw new InvalidArgumentException(
                'You must specify an Operation Type in  $operationType or $maintenanceRequest->operation'
            );
        }

        if (!is_null($operationType)) {
            $maintenanceRequest->operation = $operationType;
        }
```
Is it ok for you ?

**Comment by webmake** [comment]
Yes, it would be good :)

I would improve your snippet to check `$operationType` once:
```
        if (!is_null($operationType)) {
            $maintenanceRequest->operation = $operationType;
        } elseif ($maintenanceRequest->operation === null) {
            throw new InvalidArgumentException(
                'You must specify an Operation Type in  $operationType or $maintenanceRequest->operation'
            );
        }
```

**Comment by etiennelandais** [comment]
https://github.com/hipay/hipay-fullservice-sdk-php/releases/tag/1.10.0
