### ISSUE TITLE
Results of toArray and json_decode(toJson) are not equal

### ISSUE THREAD

**Issue by webmake** [hipay/hipay-fullservice-sdk-php#40]
Hello,

As you can see from image, `toArray` doesn't perform recursively `toArray` transform.

Also notable when executed `toJson`, it hides some properties info, as `order`, `paymentMethod`, `fraudScoring`, as a consequence those both arrays aren't equal. Main problem is, that there is no way to save data as it is in database, using `toJson` - not full info is saved, using `toArray` need manually perform recursive walk, either database will perform toString which also will hide that mentioned info.

![image](https://user-images.githubusercontent.com/5016464/46461852-695eb080-c7c8-11e8-8275-4ed56e7c14ec.png)

**Comment by etiennelandais** [comment]
Hello !

this issue has been fixed in the latest release : https://github.com/hipay/hipay-fullservice-sdk-php/releases/tag/2.0.0

regards,
