### ISSUE TITLE
Update list

### ISSUE THREAD

**Issue by webmake** [hipay/hipay-fullservice-sdk-php#41]
Hello,

I guess it was long time since update this [list](https://github.com/hipay/hipay-fullservice-sdk-php/blob/master/lib/HiPay/Fullservice/Data/PaymentProduct/Collection.php)
There are some mistakes also, ex.:
"bank-transfert", -> bank-transfer
"webmoney-transfert", -> webmoney-transfer
"klarna" -> now it exists as klarnainvoice and klarnacheckout
"postfinance-card" according site is Debit Card, not "category":"realtime-banking",
"aura" is Credit Card not "category":"realtime-banking",
and missing other supported payments

**Comment by etiennelandais** [comment]
Everything has been updated in https://github.com/hipay/hipay-fullservice-sdk-php/releases/tag/2.2.0
