### ISSUE TITLE
Timeouts for requests

### ISSUE THREAD

**Issue by webmake** [hipay/hipay-fullservice-sdk-php#43]
Hello,

is it for reason missing [timeouts for http calls](https://github.com/hipay/hipay-fullservice-sdk-php/blob/master/lib/HiPay/Fullservice/HTTP/SimpleHTTPClient.php#L67)? I am talking about `CURLOPT_CONNECTTIMEOUT`, `CURLOPT_TIMEOUT`

**Comment by legithubdeaymeric** [comment]
Hello,

No particular reason.
We will add these default values:
CURLOPT_CONNECTTIMEOUT: 30
CURLOPT_TIMEOUT: 50

So a total of 80s ...

Would that be okay with you ?

**Comment by webmake** [comment]
For me yes, but default php request execution time is 30s so be aware, maybe it should be allowed to configure by everyone needs? like with proxies

**Comment by etiennelandais** [comment]
Hello,

timeout has been added to the latest release 

https://github.com/hipay/hipay-fullservice-sdk-php/releases/tag/2.3.0

regards
