### ISSUE TITLE
Update tokenize PaymentCardToken model

### ISSUE THREAD

**Issue by webmake** [hipay/hipay-fullservice-sdk-php#44]
Related with https://github.com/hipay/hipay-fullservice-sdk-php/issues/42

Hello,

OLD tokenization v1:
```
{
  "token": "467826c081633eebca0793ac83966de1bccfc93bd3be168ac4d545abf8005597",
  "request_id": "0",
  "brand": "visa",
  "pan": "400000******0002",
  "card_holder": "Cathy Doe",
  "card_expiry_month": "12",
  "card_expiry_year": "2025",
  "issuer": "",
  "country": "US",
  "domesticNetwork": ""
}
```
NEW tokenization v2:
```
{
  "token": "2991f82432550782312e0c8075d2c956d90b54dc5683f8547fe0cc4f66314cc6",
  "request_id": "0",
  "card_hash": "ce5f096fa6bc05989c170e7c96f94432660491bd",
  "card_id": "96ada09f-a844-4956-9593-cb758630dac2",
  "brand": "VISA",
  "pan": "400000xxxxxx0002",
  "card_holder": "Cathy Doe",
  "card_expiry_month": "12",
  "card_expiry_year": "2025",
  "country": "US",
  "card_type": "CREDIT",
  "forbidden_issuer_country": false
}
```

Currently using this sdk it is imposible to extract `card_hash` which was as `token` in v1 unique value per card.

Also I see there were added new fields such as `card_id`, `card_type`, `forbidden_issuer_country`, `card_category` (maybe there are more secret fields) which were unmentioned in https://developer.hipay.com/doc-api/enterprise/token/#!/tokenization/createToken

**Comment by etiennelandais** [comment]
Hello !

It has been fixed on the latest release 

https://github.com/hipay/hipay-fullservice-sdk-php/releases/tag/2.3.0

Regards
