### ISSUE TITLE
Mapping issue : undefined index['mid']

### ISSUE THREAD

**Issue by julienbruitte** [hipay/hipay-fullservice-sdk-php#47]
Hello,

In case of error while requesting operation (like maintenance), if an error occured on the hipay API, it seems that the mid is not returned. As a result there is a php error on the OperationMapper.php , because the mid is not checked. (Juste a ? which does not perform an isset).

What are the workaround, we do not want to copy the sdk to our source code.

**Comment by legithubdeaymeric** [comment]
Hello,

You are absolutely right, the case of an API error is not handled correctly, because the API does not return all informations.

We will fix this as soon as possible.

**Comment by ahfeel** [comment]
Any update on this ?

**Comment by legithubdeaymeric** [comment]
Hi, 

It's fixed from 2.6.0

https://github.com/hipay/hipay-fullservice-sdk-php/releases/tag/2.6.0
