### ISSUE TITLE
User deprecated function: This construction method is deprecated

### ISSUE THREAD

**Issue by p4trizio** [hipay/hipay-fullservice-sdk-php#48]
using php 7.3 I receive the following error:
`User deprecated function: This construction method is deprecated. Please use an array to create your configuration. in HiPay\Fullservice\HTTP\Configuration\Configuration->__constructDirect() (line 551 of /var/www/html/vendor/hipay/hipay-fullservice-sdk-php/lib/HiPay/Fullservice/HTTP/Configuration/Configuration.php).`

**Comment by Zhigalin** [comment]
You should create the configuration with an array, like this:
`new Configuration(["apiUsername"=>$this->login, "apiPassword"=>$this->secret, "apiEnv"=>$this->environment])`

**Comment by p4trizio** [comment]
@Zhigalin thanks for the tip
