### ISSUE TITLE
OrderRequest field paymentMethod usage.

### ISSUE THREAD

**Issue by Zhigalin** [hipay/hipay-fullservice-sdk-php#49]
If the current payment method is different from Astropay/CartToken/IDeal/Qiwi/SEPA/3X/4X (which have a corresponding `Gateway\Request\PaymentMethod\*PaymentMethod` class) what value the 
`\HiPay\Fullservice\Gateway\Request\Order\OrderRequest::$paymentMethod` should assume?

P.S. There is a dead link in the README:
> HiPay Support Center — To get technical help from HiPay

which points to a not working site http://help.hipay.com/

**Comment by legithubdeaymeric** [comment]
What is the exact payment method?

You can use CardTokenPaymentMethod if paying by card
