### ISSUE TITLE
Missing request parameter

### ISSUE THREAD

**Issue by agavss** [hipay/hipay-fullservice-sdk-php#52]
The `OrderRequest ` class (https://github.com/hipay/hipay-fullservice-sdk-php/blob/6cba30a05d47233c7789b45bbfe01ae340706beb/lib/HiPay/Fullservice/Gateway/Request/Order/OrderRequest.php) is missing the `authentication_indicator` metod, as seen in the documentation: https://developer.hipay.com/online-payments/sdk-reference/sdk-php

**Comment by legithubdeaymeric** [comment]
Hello @agavss 

Yes documentation seems not up to date.

This parameter is only for CardTokenPaymentMethod  

Here: https://github.com/hipay/hipay-fullservice-sdk-php/blob/6cba30a05d47233c7789b45bbfe01ae340706beb/lib/HiPay/Fullservice/Gateway/Request/PaymentMethod/CardTokenPaymentMethod.php#L75

**Comment by Geolim4** [comment]
Hello

I would like to report other missing parameters, used for oney 3x/4x:
```
zipcode
city
country
shipto_zipcode
shipto_city
shipto_country
delivery_date
```

And maybe more.
In fact the OrderRequest should rely on the following file:
https://github.com/hipay/openapi-hipay/blob/master/enterprise/gateway.yaml

@etiennelandais

// off topic
(@legithubdeaymeric  I'm from Nantes too, can we take a moment to chat on this ?)

**Comment by lmeyer** [comment]
Hello,

I would like to report some missing parameters, seen in documentation but not in the `OrderRequest.php` class.

```
firstname 
lastname 
email
```

This parameters work when added to `CustomerBillingInfoRequest.php`  class.

Wrong

```php
$orderRequest = new OrderRequest();
$orderRequest->firstname = 'Firstname';
$orderRequest->lastname = 'lastname';
$orderRequest->email = 'email@domain.tld';
...
```

Good

```php
$orderRequest = new OrderRequest();
...
$customerBillingInfo = new CustomerBillingInfoRequest();
$customerBillingInfo->firstname = 'Firstname';
$customerBillingInfo->lastname = 'lastname';
$customerBillingInfo->email = 'email@domain.tld';
...
$orderRequest->customerBillingInfo = $customerBillingInfo;
```
