### ISSUE TITLE
3DS1 sunset

### ISSUE THREAD

**Issue by webmake** [hipay/hipay-fullservice-sdk-php#62]
Hello,

We have a question, do you allow to control 3ds version to 2 (3DS2)?

3D Secure 1 authentication protocol will be sunset (decommissioned) on the 15th of October 2022 for Visa and the 18th of October for Mastercard respectively.  After these dates, 3DS1 authentication will no longer work. Are you aware of this?

**Comment by legithubdeaymeric** [comment]
Hi webmake, 

Yes of course we are aware of this ;-)
The changes for caller are here:

https://support.hipay.com/hc/en-us/articles/360005968459-PSD2-and-Strong-Customer-Authentication-3-D-Secure-v2-compliance-and-guidance

Do you have specific question ?

**Comment by webmake** [comment]
Well, [it seems](https://github.com/hipay/hipay-fullservice-sdk-php/commit/909305cd628a827542a3069b3de5d16cad65933e#diff-1617073744c981efdcfc7f44c4456b3d73e874894108b34b8eb93784e0db13baR181) that browser_info and device_channel were added, but  firstname, lastname not, are these last two optional?

**Comment by legithubdeaymeric** [comment]
They are strongly recommended for frictionless but not mandatory.

**Comment by webmake** [comment]
Like in link I've shared, there is no possibility to do that lib/HiPay/Fullservice/Gateway/Request/Order/OrderRequest.php, because no such fields

**Comment by JBaptisteLvt** [comment]
Hello,
Please excuse us of the answer delay.

These information are already handled in the PHP SDK, in the object $orderRequest->customerBillingInfo->firstname and $orderRequest->customerBillingInfo->lastname.

https://developer.hipay.com/online-payments/sdk-reference/sdk-php#order
