### ISSUE TITLE
Open /token API to SDK

### ISSUE THREAD

**Issue by Olivier-SP** [hipay/hipay-fullservice-sdk-php#63]
In a context where we have to check cardCountry before applying fees on a transaction, we're not able to use the PHP SDK to call this API.
Would be very useful to have this API available in the SDK.
A Pull Request have been made (partially) to covers this, but nothing happened in the meantime (#51 ).
Any chance to have this in a future release ?

**Comment by legithubdeaymeric** [comment]
@Olivier-SP 

Bonjour ! 
Le pays d'émission de la carte est récupérable dans le résultat de la tokenization.

`{
  "payment_product": "visa",
  "token": "f7e73c9924c89cb64ef461f40358f148d6bde3746eeaf644324dfb8b67126e86",
  "request_id": "0",
  "card_id": "9fd81707-8f41-4a01-b6ed-279954336ada",
  "multi_use": 1,
  "brand": "VISA",
  "pan": "411111xxxxxx1111",
  "card_holder": "DD DDD",
  "card_expiry_month": "05",
  "card_expiry_year": "2024",
  "issuer": "JPMORGAN CHASE BANK, N.A.",
  "country": "US",
  "card_type": "CREDIT",
  "forbidden_issuer_country": false,
  "device_fingerprint": "0400VTMEVHGZBqEpIfq2LLtL/YybcyFYxKH7E+TSqukM9iYCP3I/gtJSIOMr0YV5w5CLdT91YnoNVrjwY1GXs7ofNvsH0boc8XXlajKgqaJOf7LRJxfedACVPRa9rcO2XMzW5sdrzcINkHpGa0Zg+WAld8FmCVUJow2J13RgHNLtyZD49HwyY1fEuavehNwNPHbn7tiEIcEzWVanHbzmopDdqilCz8QbOZkv07+M+X1lxQjvzTrky7ZgSzOI+FnoX4yKa0Yy5JnHYpN1P3Vieg1WuPBjUZezuh82+wfRuhzxdeVqMqCpok5/stEnF950AJU9Fr2tw7ZczNbAqvQx/6iBZvdaZ+9WVICZ3o0VTtSZDtydsgp6qpgeFiCsEfnG/KSZQ8q1xLNMjxaQjXA4kTayg/64AKkIGHUDlaz51qHvP1jhaPiPerYdlvDoMmrEzq/WriuIJV/uPaCMO63VKLJF2i96XNe2HYGnrbcJdCKe1iWR6TddLCGPrhQVepZfnmrlv5zrIq8W0rs3AtyvfiY2sPkz9jcB8sUSw8uSgAKvWR8azi+iT1xbnWTijTfEZhECZnv4Scx8LgtCRuP0PI9xRIEPZjLDEx1MiMp+9xUVBA4F6wwScC6ZJjrTeacbV3eUvIvFUWfXspaZ47nYJC0gMxLXrw6h637KjNXsgMEghG3NImueJKUdXLgxVCqlWwT78cFCb3XpK0K8hZCSHGBUGQbz44XiMf/eY92hNSmr+k28EssPaX5qswX9wWLJD32GEp48DVRl0oBkPCJz7Ln+v5KTIBvOIMzuTzEBdNLiXsPV6scyeMvquLCKa/QAgjUrIk9GNjedIf5MyPpjzYuuV+VhT2JQxvTdfqYAndlMe7ZEccU71S0w6bwQV+5B9Mcx6LEtcYEgIDUmlBgAVSsOV9IpG/94dXdCJuhcu7D0uboRqSsRkc8t5oqK9C2NgY68Rw6NL2GAwt8apG44isAWX3Sw7PtSQtUR3qs+07R991MQfvtZwYRXTORMSZbBA8lnmcIY8YqHbWKwLY4MxzBgJC0y5BDeC+xHyPCOzkJrb/AF2GKb28r9SxDlc5ibQ6opsC2ODMcwYCQtMuQQ3gvsR8jwjs5Ca2/wBdhim9vK/UsQ5XOYm0OqKbAtjgzHMGAkppIBae7UiPTrIWh2D/DquplcDJ40y2Dc7oc5h1YbsSjz0paGQAofAE8xAXTS4l7DQtPYEf0PHxk1gG7+dJK6MLjZZzRrB9cG3rjEFBwKZGbSUtkcJlaTDuxNT3+OiL17WHRMjDmpBc6ayypN7tbNCDrs8OZl2fACBiRq4Lfun5GwHHrDW3HSYxnPse2ZJCsq4e3f1u/ETzp5VpgkQXTQzZ2bCkUkx/iDw46OdqWNg7+/4PoTXuhr9FU8NguKENqer1nNtP8OECkk/64lKoqM3wDorceNFA82L/DmuTZotRRZEBlF3CwJErGAqHKF92svkAvvX5+GhXFa+8GxQj+MNqaUSUwrNKIi/DtaOTs8BpE7v2uiH9ul1ucbG786LSptVX76nOn46YG6deg7kF36a6bXTfC+8druyzR7++NeG1oZsUXHT8kBNDiJ/xymFf3mJc5a9O8IDqTO/brV7j+EilrJ+OE0B7OEanxH0c0ccuZJYKQjzjQXN1e0CNkmNB8SfZ/C2fG676fz3wafI/WYHE4Lnv2itJ4Ba8xmR7zn255J2L1GMcCBwYbLk5y7tWRU3eln9a65pRCqjtWByrrq0vIZi5t4t2z7pyEgXoQr6GSnEFnzcnvZoo6mPEj/ioFyFir2SiMT57p9DTPxVxy1RC8MkW8CEWFHsTCuW8o8T64jVqhRtVsWmS8B31r+l0MTBcoO4xHixePbSPzjYrYCcmtQTN8Onuu79Y4LGVkTFxfRNoX7C0Q5sponvrNzVL1lU53C3ONlZPyeLTGt54KenBr7cS4mFfW23gZ2iSO5OYg+xqj/45C8a6x4qVfuclVe3z77rQORxQNFhQzAmkNiGXlVvpCGtYcoEu5WM/L9EnbGKvcRaebU8ADouifaM+KFBBoyBBCvsG0SkAfdA/EUkKkUQghvcCNwO1SX3TiGaJFbTnRE/mtHD3RthS9QKc8soGm6Mnhv+C44pL/39GWghkLCXfqUP24RgPlHu7pIgj63upSOiz3WoKd3m1CR1VaePxL73dQzolab1vLhssH7kD6hvcfWHrKRenDvA/sexm8XoSGDkSwlzEnKiqX0iJUxB2GDXcjpghmbPTnN5ES6v4kFWgZWJFZbymN9Ond1hi/kiCHTiVQqVmutOCS6torqBwvGJwGQv0W4FaOUjAhEi1reljpY5JRcHA59trdQrakGeNnIZu5rm1J7eAai3D3ADKUOiu4ZHtobkj0dKWXX1M6wvSQS+saFLnTVI3fkiteqk9p5UQuWZI34bIrbXgIyFSLBAV7o1SvTpxEyV/65HQWUiEmM/kzym6uxSuyf9z+YW4RPB43tnLnB3Glq/7uOualj12NQQh4751P81WlwVOsIhd6jWIaJgVmYQocuXB23vjF6Dt2fCSkovzXC5kIvZvoS89eedB8JdOU26yM1k9NZsaZE+BQkwlnoBnh72Wx+DW+uEh+PN9LqSwqZ4tsHhcNcWZwYrhdLyxzFsZ3o8/1i9wXFtwdSlePKx+ilUCfY43PoifytQ14zIyZiC2r6bGGLViX2OgcwZQRLJscjpwzwcWOSDzw6M6GSJFzS1d115kMil7oEUlM9TjuEPHj/NQuV3IOAnusJJzWDiOz+NIyplBjhUWNCd0mNQ7fg+QQNZCFL2KxtaikdNNx54Dzo4CANfodUsFLw1yZMgAbJS6XKBgWYjDL29dWgpdWtfRgl1MEPdsLzf1pB7hPyXIr4Sx9mkQiFoMI2W/9XdSqFNAHr60it9gn7Yc49VmQq5mSxfAkNFF+4WKbWRaGMe5b7wTpqC7aOF/FFOZTREOLj/g==",
  "browser_info": {
    "java_enabled": false,
    "javascript_enabled": true,
    "language": "fr-FR",
    "color_depth": 30,
    "screen_height": 982,
    "screen_width": 1512,
    "timezone": "-60",
    "http_user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
    "ipaddr": "",
    "http_accept": ""
  }
}`

On souhaiterais en savoir un peu plus sur votre use case car on ne pousse pas à utiliser cette API de consulation après coup.

**Comment by Olivier-SP** [comment]
> @Olivier-SP
> 
> Bonjour ! Le pays d'émission de la carte est récupérable dans le résultat de la tokenization.
> 
> `{ "payment_product": "visa", "token": "f7e73c9924c89cb64ef461f40358f148d6bde3746eeaf644324dfb8b67126e86", "request_id": "0", "card_id": "9fd81707-8f41-4a01-b6ed-279954336ada", "multi_use": 1, "brand": "VISA", "pan": "411111xxxxxx1111", "card_holder": "DD DDD", "card_expiry_month": "05", "card_expiry_year": "2024", "issuer": "JPMORGAN CHASE BANK, N.A.", "country": "US", "card_type": "CREDIT", "forbidden_issuer_country": false, "device_fingerprint": "0400VTMEVHGZBqEpIfq2LLtL/YybcyFYxKH7E+TSqukM9iYCP3I/gtJSIOMr0YV5w5CLdT91YnoNVrjwY1GXs7ofNvsH0boc8XXlajKgqaJOf7LRJxfedACVPRa9rcO2XMzW5sdrzcINkHpGa0Zg+WAld8FmCVUJow2J13RgHNLtyZD49HwyY1fEuavehNwNPHbn7tiEIcEzWVanHbzmopDdqilCz8QbOZkv07+M+X1lxQjvzTrky7ZgSzOI+FnoX4yKa0Yy5JnHYpN1P3Vieg1WuPBjUZezuh82+wfRuhzxdeVqMqCpok5/stEnF950AJU9Fr2tw7ZczNbAqvQx/6iBZvdaZ+9WVICZ3o0VTtSZDtydsgp6qpgeFiCsEfnG/KSZQ8q1xLNMjxaQjXA4kTayg/64AKkIGHUDlaz51qHvP1jhaPiPerYdlvDoMmrEzq/WriuIJV/uPaCMO63VKLJF2i96XNe2HYGnrbcJdCKe1iWR6TddLCGPrhQVepZfnmrlv5zrIq8W0rs3AtyvfiY2sPkz9jcB8sUSw8uSgAKvWR8azi+iT1xbnWTijTfEZhECZnv4Scx8LgtCRuP0PI9xRIEPZjLDEx1MiMp+9xUVBA4F6wwScC6ZJjrTeacbV3eUvIvFUWfXspaZ47nYJC0gMxLXrw6h637KjNXsgMEghG3NImueJKUdXLgxVCqlWwT78cFCb3XpK0K8hZCSHGBUGQbz44XiMf/eY92hNSmr+k28EssPaX5qswX9wWLJD32GEp48DVRl0oBkPCJz7Ln+v5KTIBvOIMzuTzEBdNLiXsPV6scyeMvquLCKa/QAgjUrIk9GNjedIf5MyPpjzYuuV+VhT2JQxvTdfqYAndlMe7ZEccU71S0w6bwQV+5B9Mcx6LEtcYEgIDUmlBgAVSsOV9IpG/94dXdCJuhcu7D0uboRqSsRkc8t5oqK9C2NgY68Rw6NL2GAwt8apG44isAWX3Sw7PtSQtUR3qs+07R991MQfvtZwYRXTORMSZbBA8lnmcIY8YqHbWKwLY4MxzBgJC0y5BDeC+xHyPCOzkJrb/AF2GKb28r9SxDlc5ibQ6opsC2ODMcwYCQtMuQQ3gvsR8jwjs5Ca2/wBdhim9vK/UsQ5XOYm0OqKbAtjgzHMGAkppIBae7UiPTrIWh2D/DquplcDJ40y2Dc7oc5h1YbsSjz0paGQAofAE8xAXTS4l7DQtPYEf0PHxk1gG7+dJK6MLjZZzRrB9cG3rjEFBwKZGbSUtkcJlaTDuxNT3+OiL17WHRMjDmpBc6ayypN7tbNCDrs8OZl2fACBiRq4Lfun5GwHHrDW3HSYxnPse2ZJCsq4e3f1u/ETzp5VpgkQXTQzZ2bCkUkx/iDw46OdqWNg7+/4PoTXuhr9FU8NguKENqer1nNtP8OECkk/64lKoqM3wDorceNFA82L/DmuTZotRRZEBlF3CwJErGAqHKF92svkAvvX5+GhXFa+8GxQj+MNqaUSUwrNKIi/DtaOTs8BpE7v2uiH9ul1ucbG786LSptVX76nOn46YG6deg7kF36a6bXTfC+8druyzR7++NeG1oZsUXHT8kBNDiJ/xymFf3mJc5a9O8IDqTO/brV7j+EilrJ+OE0B7OEanxH0c0ccuZJYKQjzjQXN1e0CNkmNB8SfZ/C2fG676fz3wafI/WYHE4Lnv2itJ4Ba8xmR7zn255J2L1GMcCBwYbLk5y7tWRU3eln9a65pRCqjtWByrrq0vIZi5t4t2z7pyEgXoQr6GSnEFnzcnvZoo6mPEj/ioFyFir2SiMT57p9DTPxVxy1RC8MkW8CEWFHsTCuW8o8T64jVqhRtVsWmS8B31r+l0MTBcoO4xHixePbSPzjYrYCcmtQTN8Onuu79Y4LGVkTFxfRNoX7C0Q5sponvrNzVL1lU53C3ONlZPyeLTGt54KenBr7cS4mFfW23gZ2iSO5OYg+xqj/45C8a6x4qVfuclVe3z77rQORxQNFhQzAmkNiGXlVvpCGtYcoEu5WM/L9EnbGKvcRaebU8ADouifaM+KFBBoyBBCvsG0SkAfdA/EUkKkUQghvcCNwO1SX3TiGaJFbTnRE/mtHD3RthS9QKc8soGm6Mnhv+C44pL/39GWghkLCXfqUP24RgPlHu7pIgj63upSOiz3WoKd3m1CR1VaePxL73dQzolab1vLhssH7kD6hvcfWHrKRenDvA/sexm8XoSGDkSwlzEnKiqX0iJUxB2GDXcjpghmbPTnN5ES6v4kFWgZWJFZbymN9Ond1hi/kiCHTiVQqVmutOCS6torqBwvGJwGQv0W4FaOUjAhEi1reljpY5JRcHA59trdQrakGeNnIZu5rm1J7eAai3D3ADKUOiu4ZHtobkj0dKWXX1M6wvSQS+saFLnTVI3fkiteqk9p5UQuWZI34bIrbXgIyFSLBAV7o1SvTpxEyV/65HQWUiEmM/kzym6uxSuyf9z+YW4RPB43tnLnB3Glq/7uOualj12NQQh4751P81WlwVOsIhd6jWIaJgVmYQocuXB23vjF6Dt2fCSkovzXC5kIvZvoS89eedB8JdOU26yM1k9NZsaZE+BQkwlnoBnh72Wx+DW+uEh+PN9LqSwqZ4tsHhcNcWZwYrhdLyxzFsZ3o8/1i9wXFtwdSlePKx+ilUCfY43PoifytQ14zIyZiC2r6bGGLViX2OgcwZQRLJscjpwzwcWOSDzw6M6GSJFzS1d115kMil7oEUlM9TjuEPHj/NQuV3IOAnusJJzWDiOz+NIyplBjhUWNCd0mNQ7fg+QQNZCFL2KxtaikdNNx54Dzo4CANfodUsFLw1yZMgAbJS6XKBgWYjDL29dWgpdWtfRgl1MEPdsLzf1pB7hPyXIr4Sx9mkQiFoMI2W/9XdSqFNAHr60it9gn7Yc49VmQq5mSxfAkNFF+4WKbWRaGMe5b7wTpqC7aOF/FFOZTREOLj/g==", "browser_info": { "java_enabled": false, "javascript_enabled": true, "language": "fr-FR", "color_depth": 30, "screen_height": 982, "screen_width": 1512, "timezone": "-60", "http_user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36", "ipaddr": "", "http_accept": "" } }`
> 
> On souhaiterais en savoir un peu plus sur votre use case car on ne pousse pas à utiliser cette API de consulation après coup.

Bonjour et merci de votre réponse,

J'ai bien conscience que le sdk JS permet de récupérer cette information, ceci étant, le cas d'usage que je peux vous exposer est le suivant:
1/ tokenisation frontend et récupération du code country pour déterminer des frais de dossier sur des cartes étrangères et proposer un affichage dynamique
2/ au paiement, envoi du card token, du request_id ainsi que le code country sur une route API (en autres), vérification du code country (qui pourrait être falsifié) pour valider le montant des frais de dossier, puis process de création de transaction, etc...

Espérant être assez explicite.

PS: la solution de repli que nous utilisons est de faire un appel API spécifique à /token hors du SDK hipay

**Comment by legithubdeaymeric** [comment]
Merci pour votre retour détaillé.
Nous allons essayer de l'intégrer dans notre roadmap prochainement.

**Comment by JBaptisteLvt** [comment]
Bonjour !
Après vérification, cette méthode est déjà disponible dans le SDK, dans la classe SecureVaultClient, avec la méthode requestLookupToken.

Voila un exemple d'utilisation : 

```
//Create a configuration object
// By default Configuration object is configured in Stage mode (Configuration::API_ENV_STAGE)
$config = new \HiPay\Fullservice\HTTP\Configuration\Configuration(
            array(
                "apiUsername" => "YOUR_API_USERNAME",
                "apiPassword" => "YOUR_API_PASSWORD",
                "apiEnv" => Configuration::API_ENV_STAGE,
                "hostedPageV2" => true
            )
        );
 
//Instantiate client provider with configuration object
$clientProvider = new \HiPay\Fullservice\HTTP\SimpleHTTPClient($config);

 
//Create your secure vault client
$vaultClient = new \HiPay\Fullservice\SecureVault\Client\SecureVaultClient($clientProvider);

$tokenInformation = $vaultClient->requestLookupToken('<YOUR_TOKEN>');
```
