### ISSUE TITLE
soft_descriptor is missing in OrderRequest class

### ISSUE THREAD

**Issue by iamveecee** [hipay/hipay-fullservice-sdk-php#65]
I wanted to add statement descriptor, which will appear in the client's banking application, so I looked in the documentation and found that their is variable `soft_descriptor` which is used to add statement descriptor.  But in **OrderRequest** class the variable is missing and I'm unable to add it. 

So is their any other way to add the statement descriptor

Here is the link of documentation where it is mentioned  
https://support.hipay.com/hc/en-us/articles/360010582280-HiPay-Enterprise-Hosted-Fields-with-JavaScript-SDK-and-order-API

and screenshot of it.
![image](https://github.com/hipay/hipay-fullservice-sdk-php/assets/6140263/12f1c3fc-4c06-4501-bd19-6d16e055ee90)

Thanks

**Comment by JBaptisteLvt** [comment]
Hello !
Thanks for your report, we will add this parameter in the SDK !

**Comment by JBaptisteLvt** [comment]
Hello !
This was added in the version 2.15.0 of the SDK !
